#内网生产用：需改名为application.yml.tmpl，放在\xinfras_upgrade\xinfras\config下使用
server:
  port: 8085
  servlet:
    context-path: /xinfras
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: xinfras
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: {{getv "/nginx/host"}}:8848
  rabbitmq:
    host: {{getv "/rabbitmq/host"}}
    port: {{getv "/rabbitmq/port"}}
    username: {{getv "/rabbitmq/user"}}
    password: {{getv "/rabbitmq/passwd"}}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{{getv "/mariadb/host"}}:{{getv "/mariadb/port"}}/infras?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: {{getv "/mariadb/user"}}
    password: {{getv "/mariadb/passwd"}}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true

  devtools:
    restart:
      enabled: true
#      additional-paths: src/main/java

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cmbc.infras.system.domain
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl:

#登陆验证接口地址
authorize:
  clientId: G26
  secret: Ghepf1UC6GNkvV81
  authorizeUrl: http://spsso.cmbc.com.cn:8008/SOAM/oauth/authorize
  redirectUrl: http://40.2.160.91:18080/loginaccess/toLoginAccess
  tokenUrl: http://40.45.13.36:14100/SOAM/oauth/token
  userInfoUrl: http://40.45.13.36:14100/SOAM/user/getuserinfo
  logOutUrl: http://iamtest.dev.cmbc.cn:8028/SOAM/oauth/logout
  whiteString: ".js,.png,.ttf,.woff,.css,.json,.webm,/logout,/authorizeCallback,/lastCount,/toLoginAccess,/mobileAuthCallback,/logout,\
  /socket,/alarm/authCode,/userBankId,/toAlarmPage,/toLastCount,/event.html,/app/callback,/loginProcess,/workBench,/head/siteStatis,\
  /head/evaluates,/config/bankSpotListFromKeByResourceId,/config/bankSpotLatest,/mobile,/loginPortalKe,/formMessage/inform"
  redirectAlarmPage: /infras_web/alarm/event.html

mobile:
  #代办消息服务认证用
  authorize:
    url: http://oagateway.cmbc.com.cn/cmbc-oauth-regster/cmbc-oauth-regster/oauth/token
    client_id: QHDLHJJK_4eb02e5b-c20a-4fe2-bac2-9017936cba5b
    client_secret: QHDLHJJK_bbcf802a-8650-46c5-a965-6c7bca9eb20c1664178867
    username: QHDLHJJK
    password: cmbc@95568
    grant_type: password
  oa:
    server: http://oagateway.cmbc.com.cn/sqs #生产ip 40.55.95.4:80

event-mq:
  queue: eventTopicQueue
  exchange: storage_exchange
  routing: storage.eventtopic.#

redis.addrs: {{getv "/redis/addrs"}}
redis.passwd: {{getv "/redis/passwd"}}
redis.cluster: {{getv "/redis/cluster"}}

#feignClient-请求数据地址端口
ke-rpc:
  server: {{getv "/nginx/protocol"}}://{{getv "/nginx/host"}}:{{getv "/nginx/port"}}
ke:
  encrtyKey: wanguoshuju12345
simple:
  admin:
    url: {{getv "/nginx/protocol"}}://{{getv "/nginx/host"}}:{{getv "/nginx/port"}}/api/admin
    index:
      url: {{getv "/nginx/protocol"}}://{{getv "/nginx/host"}}:{{getv "/nginx/port"}}
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#UserBankRpc
bankRpc:
  name: xinfras
  api: /xinfras/userBankId

#流程表单根据银行名查银行ID-表单号
flowForm:
  evaluate:
    formId: 202112091604466996
  partol:
    formId: OnSiteInspectionTask
  maintain:
    formId: MaintenanceOperation
  deduce:
    formId: EmergencyOperation
  score:
    formId: 202112091604466996

#移动OA认证后跳转的首页
infras.oa_home: http://msmoatest.cmbc.com.cn:8899/infras/info/phone.html
infras.home.portal: /portal
#YmlConfig.getBoolValue(1,true返回true)
infras.common.configs: "{'no-verify':'true','switch':'true', 'checkLoginKe':'1', 'loginKeUrl':'http://40.2.160.86:18080/api/v3/xsso/token/check'}"

#自定义注解-结果LGO是否输出
#有的查询结果太长
self.annotation.log.open: false

#生产运营部生产调度中心-三方接口调用
interface:
  switchRefresh: close
  lastCount:
    clientId: itptl
    code: Q6F1hbGPcLOSSeUlugxpMNMJmygcRZSSc0fvm7Cb8i26GOFtblZ6n6qS5D5HFPlMlSVWCZKDyBvELJLN0IK5RQNLxKEBxQEJzOENzN


